### ISSUE TITLE
Integrating slide picker and saving slide selection in local storage

### ISSUE THREAD

**Issue by namandangi** [dgutman/osdAutoRegistration#14]
To-do:

1. Integrate the slide selection dialog box with the other existing examples 
2. Add a mechanism to save the currently selected slide in the local storage for auto-populating the viewer on page refresh

**Comment by pearcetm** [comment]
@namandangi @dgutman Completed for the paper demo app. It would be more complicated to integrate this with the original app, and for now is not necessary.

**Comment by dgutman** [comment]
The original demo is not worth doing anything with.. just a reference

**Comment by namandangi** [comment]
@pearcetm the latest merge on main seems to be broken? The slide picker still doesn't function (should the slide picker work out of the box or is there something that needs to be done to set it up?) and the create home images also seems to have stopped working. 

On checking logs, the home images were working fine at 4efece2. 
The browser console keeps throwing $().dialog/imageSelectionWindow.dialog is not a function

**Comment by pearcetm** [comment]
Reopened the issue. Will address much of the buggy behavior in an incoming PR.

`.dialog` is part of jqueryui. That is included in the `packages.json` and included in the HTML file as a script tag - you may have to update your packages.

**Comment by pearcetm** [comment]
@namandangi I think the biggest issue you were having is that `jqueryui` was missing. This was apparently preventing the script from creating the dialog window. If you update packages, it should automatically pull in what you need. If it doesn't, open a new issue and we can sort it out there.

There are more changes here as well (mostly under the hood). I had started on some further changes in my same branch after making the previous PR, which had broken the existing `paper` demo, so I fixed that up. It's working well for me as of now though.
